name: Release Chrome Extension

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:

  release:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Create Package
        run: |
          mkdir release
          zip -r release/smart-tab-organizer.zip . \
            -x ".git/*" \
            -x ".github/*" \
            -x "node_modules/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/smart-tab-organizer.zip